### ISSUE TITLE
DPD "resend download link" not triggering an email

### ISSUE THREAD

**Issue by jrosebr1** [Py-Image/dpd-helpscout-wordpress#4] opened 2018-09-16 13:40 UTC
I've debugged with a handful of test email addresses that I've used, including one customer one, but but I'm not receiving any download link emails. I'm not sure how to debug that one other than I checked my DPD logs for each customer and they are not logging the email being resent. Something appears to be breaking along the way..

**Comment by d4mation** [comment] 2018-09-17 12:27
Did the Chrome Extension report back any errors? If it is failing at any step, it is supposed to tell you which step it failed at. If it succeeds, it is also supposed to report back the download link so that it can be added to the message body.

**Comment by jrosebr1** [comment] 2018-09-17 12:29
How can I check the Chrome Extension errors? Is it logged to `console.log`? Or is it logged on the actual HS page?

**Comment by d4mation** [comment] 2018-09-17 12:30
It will pop up as a JS Alert, so any data it reports back (Success or Failure) should appear on-screen.

**Comment by d4mation** [comment] 2018-09-17 12:41
Also, whenever it hits these exceptions, I made sure that a more detailed error message got sent to `wp-content/debug.log` if [`WP_DEBUG` and `WP_DEBUG_LOG` are enabled](https://codex.wordpress.org/WP_DEBUG).

**Comment by jrosebr1** [comment] 2018-09-17 12:56
Got it.

No, there was no JS alert whatsoever. There was no "Success" or "Failure" message. I must not have had `WP_DEBUG` and `WP_DEBUG_LOG` set either as I'm not seeing `wp-content/debug.log` on the server.

**Comment by d4mation** [comment] 2018-09-17 13:01
Huh, that's strange that it didn't report anything back to you 🤔 

If you could set those constants and try again I'd appreciate it!

**Comment by jrosebr1** [comment] 2018-09-17 15:45
I've enabled both `WP_DEBUG` and `WP_DEBUG_LOG`. Still no dice. I've recorded a screencast showing my process:

https://www.dropbox.com/s/pp0brembdj6eipt/example_of_bug.mp4?dl=0

**Comment by d4mation** [comment] 2018-09-17 16:02
Oh, wow, that was immediate. That should have taken longer. 

To confirm, you're hosting the WP side at ash.pyimagesearch.com, right? Is there anything strange in your JS Console? I wonder if it is trying to throw the Alert for an Error, but since it is expecting an Error message _from the server_ it is failing.

https://github.com/Py-Image/dpd-helpscout-chrome/blob/de6d55274d489c182d76cfbbb9730cd9e492c331/src/inject/inject.js#L96-L101

**Comment by jrosebr1** [comment] 2018-09-17 16:41
Confirmed, I'm using the Ash server to run the plugin. I just checked the console. It's indeed a 500 server error:

<img width="1286" alt="screen shot 2018-09-17 at 12 40 04 pm" src="https://user-images.githubusercontent.com/759645/45636841-d6f3a880-ba76-11e8-8883-ebe5a12f0ee7.png">

Checking the Apache error log I see the following:

```
PHP Fatal error:  Arrays are not allowed in class constants in /home/adrian/dpd-helpscout-wordpress/core/library/phpwebdriver/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 32, referer: https://secure.helpscout.net/conversation/664664542/97862/?folderId=965368
```

**Comment by d4mation** [comment] 2018-09-17 17:30
What's your PHP Version? I wonder if this is the result of an outdated PHP. 

Arrays have been allowed in Class Constants since PHP 5.6+ from what I can tell.

**Comment by jrosebr1** [comment] 2018-09-17 17:37
The server is running PHP 5.5.9.

**Comment by d4mation** [comment] 2018-09-17 17:52
Are you able to update it? 5.5.x has been at EOL for a while it seems: http://php.net/supported-versions.php

This issue with the PHP Webdriver library is known, but all solutions seem to point to updating PHP due to 5.5.x not being supported any longer.

5.6.x and 7.0.x are fast approaching EOL as well.

**Comment by jrosebr1** [comment] 2018-09-17 18:00
I can't update PHP on this particular server. I may be able to try on a different one but that will change the endpoint URLs.

**Comment by d4mation** [comment] 2018-09-17 18:03
If you want to try this on a different server with PHP 5.6+, let me know and I'll swap the Endpoint around in the Chrome Extension. 👍 

It would then also need updated on your end for the HelpScout App.

I'm sorry that there doesn't appear to be another good work around for this.

**Comment by jrosebr1** [comment] 2018-09-17 19:10
I can try it on a different server. Let's use `jobs.pyimagesearch.com`.

**Comment by d4mation** [comment] 2018-09-17 19:36
Just swapped out the URL used in the Chrome Extension. A re-pull will correct that 👍

**Comment by d4mation** [comment] 2018-09-17 20:21
Minor Correction, a pulling the latest `master` _and reloading the unpacked extension itself_.

**Comment by jrosebr1** [comment] 2018-09-17 20:42
I think we're almost there! Now there is ~3 second delay between hitting the "Resend Download" link and the following `window.alert`:

<img width="440" alt="screen shot 2018-09-17 at 4 38 18 pm" src="https://user-images.githubusercontent.com/759645/45649132-80976180-ba98-11e8-84ee-767bbd244106.png">

Looking at the Selenium log I see:

```
20:34:27.989 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
20:38:10.033 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, chromeOptions: {args: [--start-maximized], binary: }}
20:38:10.042 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac) on port 29457
Only local connections are allowed.
```

**Comment by d4mation** [comment] 2018-09-17 21:00
Are you running `run-selenium.sh` or `run-selenium-headless.sh`?

I had some oddities with `run-selenium.sh` in my development environment because in order to get an X Server running I had to log in as actual `root` to access it via GUI rather than CLI (because I normally log in with some auto-generated SSH Keys and I am unsure of how to do that from the login prompt) and Chrome doesn't play nicely when you're logged in as `root`. I had to add this line to make it work: https://github.com/Py-Image/dpd-helpscout-wordpress/blob/6206b6d15829cd59beda6349186c0a3c32ad4187/core/rest/pyis-dpd-helpscout-rest.php#L425

`run-selenium-headless.sh` I have had a lot less issues with overall (from a setup standpoint, once you have them working on your machine they're identical really), but it doesn't give you the visual feedback that can be helpful when debugging.

**Comment by jrosebr1** [comment] 2018-09-17 21:22
I was using `run-selenium.sh` but instead running `run-selenium-headless.sh` did the trick 😄 

I got the "Failed to login to DPD" error message the first time, but when I closed the tab and came back it worked.

The `window.alert` displayed but the problem is that I cannot copy and paste. Maybe a `window.prompt` with the URL as the default value instead?

**Comment by d4mation** [comment] 2018-09-18 14:39
Huh, that's weird. I can highlight and copy from `window.alert` just fine. But I'll give `window.prompt` a shot for you 👍

**Comment by d4mation** [comment] 2018-09-18 15:00
Just pushed fixes for this. You'll need to pull `master` for both the WP Plugin and the Chrome Extension (and reload the Chrome Extension).

I went ahead and made the Chrome Extension also detect the Server URL based on the HelpScout App Response, so if you need to change the server again in the future the Chrome Extension won't require any tweaks 👍

**Comment by jrosebr1** [comment] 2018-10-10 13:25
I updated the WP plugin as well as the Chrome extension, then updated the endpoint URL for the HS app. I also started the headless Selenium server, but now when I try to generate new download links I receive the following error in the JS console:

<img width="1286" alt="screen shot 2018-10-10 at 9 24 02 am" src="https://user-images.githubusercontent.com/759645/46739356-605d5b80-cc6e-11e8-80db-4e6bac924ff2.png">

That error occurs when clicking the "Resend Download Link" button.

**Comment by d4mation** [comment] 2018-10-10 14:13
That is very odd. It is calling `.replace()` on the ID Attribute of the Active Element (The element you just clicked) and that element definitely has an ID (As of https://github.com/Py-Image/dpd-helpscout-wordpress/commit/0fb219fcaac79eb59eea536015644a7b1cf0cb0e)

The `.replace()` call in the Chrome Extension was added in https://github.com/Py-Image/dpd-helpscout-chrome/commit/6bb5ba99fbb21fcd1be96dd5766a5c930a41921a#diff-048ffcb235086162612c6feffebd6996 on the same day.

I am not sure why this would be happening unless `document.activeElement` was returning the wrong element or otherwise the repos were not fully up-to-date on your machine. Can you double-check that for me by doing a `git pull` for both? If this persists, I will throw some `console.log()`s into the Chrome Plugin to see what `document.activeElement` is on your browser in this case.

**Comment by d4mation** [comment] 2018-10-10 14:29
Also, be sure to "reload" the Chrome Extension after every `git pull`. Although I think the issue here may lie with the WordPress Plugin rather than the Chrome Extension.

**Comment by jrosebr1** [comment] 2018-10-10 14:54
I did a `git pull origin master` on both. I also reloaded the Chrome plugin by going to `chrome://extensions/` and clicking the "Refresh" icon underneath the plugin name. I think we should add some `console.log` calls to see what's going on.

**Comment by d4mation** [comment] 2018-10-10 15:11
Just added some Console Logs to the Chrome Extension. Let me know what it shows 👍 

I had the thought that maybe HelpScout was sanitizing out the IDs in the response now, but I checked on my end and I can still see them:

![image](https://user-images.githubusercontent.com/7770631/46746420-129c1f80-cc7d-11e8-96a5-9d525e2d21e7.png)

The `console.log()`s succeeded on my end, so we'll have to see if it shows something different on your end.

**Comment by jrosebr1** [comment] 2018-10-10 19:07
Here is the output of `console.log`:

<img width="1392" alt="screen shot 2018-10-10 at 3 06 34 pm" src="https://user-images.githubusercontent.com/759645/46759756-2a37d000-cc9e-11e8-924d-06aae840dcad.png">

**Comment by d4mation** [comment] 2018-10-10 19:13
That's really strange. `document.activeElement` does have the clicked button, but it doesn't have the HTML ID in there. 

Have you tried this on a different Ticket? If you have the latest `master` branch for the plugin on your server my only other guess would be that the response has been cached somehow.

**Comment by BigActual** [comment] 2018-10-10 20:00
Adrian, I've been looking through this. Is it possible that the latest changes haven't been pulled down? The output in the JavaScript console looks like it's the result of an earlier version.

**Comment by BigActual** [comment] 2018-10-10 20:01
@d4mation could you reverify that the latest version is available for Adrian. Maybe there's a hiccup in the last iteration?

**Comment by d4mation** [comment] 2018-10-10 20:03
@BigActual Yes, all the changes are in `master` and IDs were added to those elements on August 10th. It is very odd that they're not showing. 🤔

**Comment by jrosebr1** [comment] 2018-10-11 09:03
> Have you tried this on a different Ticket? If you have the latest master branch for the plugin on your server my only other guess would be that the response has been cached somehow.

Yes, I tried on multiple tickets on two separate machines. In both cases I had the same error.

>  Is it possible that the latest changes haven't been pulled down? 

I'm running https://github.com/Py-Image/dpd-helpscout-chrome/commit/a6f5a7c0f8e4aa6d4e7e3e74561c9f91d0b0290c on the dpd-helpscout-chrome repo and f961003e6826e5606b8c2c6ebcc9f66a009b989f for the dpd-helpscout-wordpress repo.

**Comment by d4mation** [comment] 2018-10-11 11:40
^ I only edited your comment to make the commit hashes links

That is super weird. Those commit hashes are latest. 

I just pushed a new commit to the WP Plugin which will dump some debug info to the `/example-json/` directory and will hopefully help rule out some things like caching or HelpScout sanitizing different Attributes on your end. 

Once you've put those changes on the server could you view a ticket, grab those files via SFTP, and then send them to me via Slack, please?

--- 

Edit: There were no updates to the Chrome Extension, I just realized I referenced the Commit wrong so I commented on the Commit to tie it to the Issue.

**Comment by jrosebr1** [comment] 2018-10-12 09:25
I just pulled down the latest update and try to run the test but I don't see an `example-json` directory -- where is that directory created? Let me know and I'll double-check.

I also ran a second test where I _purposely_ killed Selenium and try the "Resend download link" button. The JavaScript console reported the same error as before which makes me think it's actually an issue with the plugin correctly connecting to the server. Does that sound about right?

**Comment by d4mation** [comment] 2018-10-12 11:32
Ah, sorry. The `/example-json/` directory is within the plugin itself. I have it in `.gitignore` because I was using it during development to hold things like example cURL commands and data structures for HelpScout and DPD for reference. 

The reason the JavaScript reports the same error is because it grabs the REST API Endpoint to hit using the Button's ID. So if it cannot grab the button ID, it cannot make a request to the server at all. I couldn't use `data` attributes or something else more standard because HelpScout would strip them out. 

So, if we can see what gets dumped into `/example-json/` for you, we can see what's happening with the Button IDs.

**Comment by jrosebr1** [comment] 2018-10-14 17:12
I did an `ls` of the plugin directory but I didn't see the `example-json` directory:

```
$ ls
core          gulp         package.json       pyis-dpd-helpscout.php  run-selenium-headless.sh  setup-selenium.sh
gruntfile.js  gulpfile.js  package-lock.json  README.md               run-selenium.sh
```

I then manually created it via `mkdir` and tried again, just in case the plugin didn't automatically create the directory. After trying to reactivate a download again I went back to the `example-json` directory and found that it is empty -- the plugin is not updating the directory.

Furthermore, when I check out the output log of `run-selenium-headless.sh` I'm seeing no log of any connections being made ((same is true for `run-selenium.sh` as well). I don't think the Chrome extension is properly connecting to the server.

**Comment by d4mation** [comment] 2018-10-14 23:11
> Furthermore, when I check out the output log of run-selenium-headless.sh I'm seeing no log of any connections being made ((same is true for run-selenium.sh as well). I don't think the Chrome extension is properly connecting to the server.

This is because if the JavaScript in the Chrome Extension is unable to see the Button ID, then it will not attempt to make a connection to Selenium. 

Can I have SFTP/SSH to the server that hosts jobs.pyimagesearch.com so I can take a look? This all is very, very odd.

**Comment by jrosebr1** [comment] 2018-10-15 08:45
Just sent them over via Slack.

**Comment by d4mation** [comment] 2018-10-15 11:34
That is so incredibly weird. I confirmed that the code to make the files in `/example-json/` was there and that the Button IDs existed in the HTML Response to HelpScout on initial load.

One more thing to check: Is the HelpScout App added to HelpScout as using jobs.pyimagesearch.com? Or is it still using ash.pyimagesearch.com? That would explain why the `/example-json/` files aren't being created and possibly why the Button IDs aren't showing.

**Comment by jrosebr1** [comment] 2018-10-15 11:56
> Is the HelpScout App added to HelpScout as using jobs.pyimagesearch.com? Or is it still using ash.pyimagesearch.com? 

It is using jobs.pyimagesearch.com. Please see Slack for a screenshot.

**Comment by d4mation** [comment] 2019-01-22 17:18
This no longer applies since the Chrome Extension has been deprecated.

**Closed as completed by d4mation** 2019-01-22 17:18 UTC
Labels: bug
